#!/bin/bash
##############################################
##                                          ##
##  Menu                                    ##
##  Launches menu_kali-1.py                 ##
##  Best autostarted through ~/.profile     ##
##                                          ##
##############################################


export FRAMEBUFFER=/dev/fb0
export MENUDIR="/home/pi/pitftmenu/"
startpage="menu_kali-1.py"
#startpage="menu_8button.py"
/usr/bin/clear

/usr/bin/env python $MENUDIR$startpage
